name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Zip files
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r ${{ github.event.release.name }}.zip . -x ".*"

      - name: Upload to Modrinth
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: 8ZiCD9vV
          featured: true
          status: listed
          channel: release
          name: ${{ github.event.release.name }}
          version: ${{ github.event.release.tag_name }}
          changelog: ${{ github.event.release.body }}
          loaders: |-
            minecraft
          game-versions: |-
            1.21
            1.21.1
            1.21.2
            1.21.3
            1.21.4
            1.21.5
          files: ${{ github.event.release.name }}.zip